import type { DashboardSnapshot } from '@/core/domain/dashboard/entities';

export const mockDashboardSnapshot: DashboardSnapshot = {
  farm: {
    id: 'farm-001',
    name: "Thabo's Farm",
    farmerName: 'Thabo',
    location: 'Limpopo, South Africa',
    region: 'Limpopo',
    country: 'South Africa',
    hectares: 10,
    sensorCoverageLabel: '7/7 sensors active',
    liveTemperatureC: 24,
  },
  overview: {
    kpis: [
      {
        label: 'Healthy fields',
        value: '2 / 4',
        detail: 'Two fields are in strong condition and two need attention.',
        tone: 'good',
      },
      {
        label: 'Average moisture',
        value: '53%',
        detail: 'Field D is pulling the farm-wide average down.',
        tone: 'warning',
      },
      {
        label: 'Expected yield',
        value: '3.5 t/ha',
        detail: 'Forecast for June if irrigation actions land on time.',
        tone: 'info',
      },
      {
        label: 'Urgent actions',
        value: '3',
        detail: 'Moisture, disease, and low-battery interventions are queued.',
        tone: 'critical',
      },
    ],
    recommendations: [
      {
        title: 'Start irrigation on Field D',
        field: 'Field D',
        description: 'Moisture is at 28%. Run the drip line for 4 hours before 18:30.',
        tone: 'critical',
      },
      {
        title: 'Treat leaf spot in Field B',
        field: 'Field B',
        description: 'Apply fungicide inside the next 48 hours to avoid spread.',
        tone: 'warning',
      },
      {
        title: 'Pre-book maize harvest',
        field: 'Field A',
        description: 'Current maize prices support reserving a buyer before the peak window.',
        tone: 'info',
      },
    ],
    yieldForecast: [
      { month: 'Jan', actual: 2.1, forecast: 2.3 },
      { month: 'Feb', actual: 2.4, forecast: 2.5 },
      { month: 'Mar', actual: 2.8, forecast: 2.7 },
      { month: 'Apr', actual: 3.1, forecast: 3.0 },
      { month: 'May', actual: 2.9, forecast: 3.2 },
      { month: 'Jun', actual: null, forecast: 3.5 },
      { month: 'Jul', actual: null, forecast: 3.8 },
    ],
  },
  cropHealth: {
    fields: [
      {
        id: 1,
        name: 'Field A - Maize',
        hectares: 4.2,
        status: 'healthy',
        moisture: 68,
        ndvi: 0.82,
        lastScan: '2h ago',
        crop: 'Maize',
        location: 'North Plot',
      },
      {
        id: 2,
        name: 'Field B - Tomatoes',
        hectares: 1.8,
        status: 'warning',
        moisture: 42,
        ndvi: 0.61,
        lastScan: '4h ago',
        crop: 'Tomatoes',
        location: 'South Plot',
      },
      {
        id: 3,
        name: 'Field C - Spinach',
        hectares: 0.9,
        status: 'healthy',
        moisture: 74,
        ndvi: 0.88,
        lastScan: '1h ago',
        crop: 'Spinach',
        location: 'East Plot',
      },
      {
        id: 4,
        name: 'Field D - Sorghum',
        hectares: 3.1,
        status: 'alert',
        moisture: 28,
        ndvi: 0.45,
        lastScan: '6h ago',
        crop: 'Sorghum',
        location: 'West Plot',
      },
    ],
    radarMetrics: [
      { metric: 'Leaf Health', A: 88, B: 54, C: 92, D: 41 },
      { metric: 'Root Vigour', A: 82, B: 70, C: 85, D: 35 },
      { metric: 'Moisture', A: 68, B: 42, C: 74, D: 28 },
      { metric: 'Nutrients', A: 79, B: 66, C: 80, D: 55 },
      { metric: 'Pest Risk', A: 92, B: 60, C: 95, D: 40 },
      { metric: 'Yield Est.', A: 85, B: 58, C: 88, D: 38 },
    ],
    diseaseScans: [
      {
        field: 'Field B',
        disease: 'Leaf Spot',
        confidence: 84,
        severity: 'Moderate',
        action: 'Apply fungicide within 48h.',
      },
      {
        field: 'Field D',
        disease: 'Root Rot Risk',
        confidence: 71,
        severity: 'High',
        action: 'Reduce irrigation and improve drainage.',
      },
      {
        field: 'Field A',
        disease: 'None detected',
        confidence: 98,
        severity: 'Clear',
        action: 'Continue monitoring.',
      },
      {
        field: 'Field C',
        disease: 'None detected',
        confidence: 96,
        severity: 'Clear',
        action: 'Continue monitoring.',
      },
    ],
    recommendations: [
      {
        title: 'Apply fungicide',
        field: 'Field B',
        description: 'Leaf spot probability is high enough to justify preventive treatment.',
        tone: 'warning',
      },
      {
        title: 'Inspect drainage',
        field: 'Field D',
        description: 'Soil readings suggest stress that could turn into root rot after rainfall.',
        tone: 'critical',
      },
      {
        title: 'Schedule a fresh NDVI scan',
        field: 'All fields',
        description: 'Run a new multispectral capture after Wednesday rain for cleaner variance checks.',
        tone: 'info',
      },
    ],
  },
  soil: {
    metrics: [
      { time: '06:00', moisture: 62, temp: 18, pH: 6.4 },
      { time: '08:00', moisture: 65, temp: 19, pH: 6.5 },
      { time: '10:00', moisture: 60, temp: 22, pH: 6.4 },
      { time: '12:00', moisture: 55, temp: 26, pH: 6.3 },
      { time: '14:00', moisture: 50, temp: 28, pH: 6.2 },
      { time: '16:00', moisture: 48, temp: 27, pH: 6.3 },
      { time: '18:00', moisture: 52, temp: 24, pH: 6.4 },
      { time: '20:00', moisture: 58, temp: 21, pH: 6.5 },
    ],
    nodes: [
      {
        id: 'SN-01',
        field: 'Field A',
        moisture: 68,
        pH: 6.4,
        temp: 24,
        nitrogen: 85,
        phosphorus: 62,
        potassium: 78,
      },
      {
        id: 'SN-02',
        field: 'Field B',
        moisture: 42,
        pH: 6.1,
        temp: 26,
        nitrogen: 58,
        phosphorus: 44,
        potassium: 55,
      },
      {
        id: 'SN-03',
        field: 'Field C',
        moisture: 74,
        pH: 6.7,
        temp: 22,
        nitrogen: 88,
        phosphorus: 70,
        potassium: 82,
      },
      {
        id: 'SN-04',
        field: 'Field D',
        moisture: 28,
        pH: 5.8,
        temp: 29,
        nitrogen: 40,
        phosphorus: 35,
        potassium: 42,
      },
    ],
    recommendations: [
      {
        title: 'Increase phosphorus on Field B',
        field: 'Field B',
        description: 'A targeted NPK 2:3:2 application will help root development before rain arrives.',
        tone: 'warning',
      },
      {
        title: 'Protect moisture on Field C',
        field: 'Field C',
        description: 'Moisture is healthy. Hold irrigation and let forecast rainfall top up naturally.',
        tone: 'good',
      },
      {
        title: 'Correct acidic drift',
        field: 'Field D',
        description: 'pH 5.8 is low for sorghum. Plan a lime adjustment on the next soil treatment cycle.',
        tone: 'critical',
      },
    ],
  },
  alerts: {
    items: [
      {
        id: 1,
        type: 'alert',
        field: 'Field D',
        message: 'Critical moisture deficit detected. Irrigation recommended immediately.',
        time: '6 min ago',
        iconLabel: 'Water',
      },
      {
        id: 2,
        type: 'warning',
        field: 'Field B',
        message: 'Early-stage leaf spot detected via AI scan.',
        time: '1h ago',
        iconLabel: 'Leaf',
      },
      {
        id: 3,
        type: 'info',
        field: 'All Fields',
        message: 'Rain forecast Wednesday to Thursday. Adjust irrigation schedules.',
        time: '4h ago',
        iconLabel: 'Cloud',
      },
      {
        id: 4,
        type: 'success',
        field: 'Field C',
        message: 'Irrigation cycle completed and moisture has normalised.',
        time: '5h ago',
        iconLabel: 'Check',
      },
      {
        id: 5,
        type: 'warning',
        field: 'Sensor SN-04',
        message: 'Battery is at 15%. Field telemetry may degrade within the next 24 hours.',
        time: '12 min ago',
        iconLabel: 'Battery',
      },
    ],
  },
  market: {
    prices: [
      { crop: 'Maize', price: 'R 4,280', unit: '/ton', change: '+3.2%', trend: 'up', buyers: 8 },
      { crop: 'Tomatoes', price: 'R 12,500', unit: '/ton', change: '-1.4%', trend: 'down', buyers: 12 },
      { crop: 'Spinach', price: 'R 8,900', unit: '/ton', change: '+6.8%', trend: 'up', buyers: 5 },
      { crop: 'Sorghum', price: 'R 3,100', unit: '/ton', change: '+0.9%', trend: 'steady', buyers: 3 },
    ],
    buyers: [
      {
        id: 1,
        name: 'FreshMart Johannesburg',
        type: 'Retailer',
        crops: ['Maize', 'Spinach'],
        rating: 4.8,
        distance: '120 km',
        verified: true,
        priceOffer: 'R 4,350 / ton',
      },
      {
        id: 2,
        name: 'Agri Export SA',
        type: 'Exporter',
        crops: ['Maize', 'Sorghum'],
        rating: 4.6,
        distance: '85 km',
        verified: true,
        priceOffer: 'R 4,100 / ton',
      },
      {
        id: 3,
        name: 'Community Co-op Limpopo',
        type: 'Co-operative',
        crops: ['Tomatoes', 'Spinach'],
        rating: 4.9,
        distance: '32 km',
        verified: true,
        priceOffer: 'R 12,200 / ton',
      },
      {
        id: 4,
        name: 'Spar Distribution Centre',
        type: 'Retail Chain',
        crops: ['Tomatoes'],
        rating: 4.4,
        distance: '210 km',
        verified: true,
        priceOffer: 'R 13,000 / ton',
      },
    ],
    priceHistory: [
      { week: 'W1', maize: 3900, tomatoes: 11200, spinach: 7800, sorghum: 2900 },
      { week: 'W2', maize: 4050, tomatoes: 11800, spinach: 8100, sorghum: 3000 },
      { week: 'W3', maize: 4120, tomatoes: 12100, spinach: 8400, sorghum: 3050 },
      { week: 'W4', maize: 4280, tomatoes: 12500, spinach: 8900, sorghum: 3100 },
    ],
  },
  sensors: {
    nodes: [
      { id: 'SN-01', field: 'Field A', battery: 92, signal: 'Strong', lastPing: '2m ago', status: 'online' },
      { id: 'SN-02', field: 'Field B', battery: 67, signal: 'Good', lastPing: '5m ago', status: 'online' },
      { id: 'SN-03', field: 'Field C', battery: 41, signal: 'Weak', lastPing: '8m ago', status: 'online' },
      { id: 'SN-04', field: 'Field D', battery: 15, signal: 'Poor', lastPing: '22m ago', status: 'warning' },
      { id: 'SN-05', field: 'Field A', battery: 88, signal: 'Strong', lastPing: '1m ago', status: 'online' },
    ],
    networkStats: [
      { label: 'Data points collected today', value: '14,832', good: true },
      { label: 'Average transmission latency', value: '340 ms', good: true },
      { label: 'Packet loss rate', value: '0.4%', good: true },
      { label: 'Uptime (30 days)', value: '99.1%', good: true },
      { label: 'Nodes needing maintenance', value: '2', good: false },
    ],
  },
  weather: {
    current: {
      temp: 24,
      humidity: 58,
      wind: 12,
      condition: 'Partly Cloudy',
    },
    hourly: [
      { time: '06:00', temp: 17, rain: 5, icon: 'cloud-sun' },
      { time: '08:00', temp: 19, rain: 5, icon: 'cloud-sun' },
      { time: '10:00', temp: 22, rain: 0, icon: 'sun' },
      { time: '12:00', temp: 24, rain: 0, icon: 'sun' },
      { time: '14:00', temp: 26, rain: 0, icon: 'sun' },
      { time: '16:00', temp: 25, rain: 10, icon: 'cloud-sun' },
      { time: '18:00', temp: 22, rain: 15, icon: 'cloud-sun' },
      { time: '20:00', temp: 19, rain: 5, icon: 'cloud-moon' },
    ],
    extended: [
      {
        day: 'Monday',
        date: '31 Mar',
        high: 26,
        low: 14,
        rain: 10,
        humidity: 52,
        wind: 10,
        condition: 'Mostly Sunny',
        icon: 'cloud-sun',
      },
      {
        day: 'Tuesday',
        date: '1 Apr',
        high: 24,
        low: 13,
        rain: 25,
        humidity: 60,
        wind: 14,
        condition: 'Partly Cloudy',
        icon: 'cloud-sun',
      },
      {
        day: 'Wednesday',
        date: '2 Apr',
        high: 21,
        low: 12,
        rain: 70,
        humidity: 78,
        wind: 18,
        condition: 'Rain Expected',
        icon: 'cloud-rain',
      },
      {
        day: 'Thursday',
        date: '3 Apr',
        high: 18,
        low: 10,
        rain: 85,
        humidity: 88,
        wind: 22,
        condition: 'Heavy Rain',
        icon: 'cloud-lightning',
      },
      {
        day: 'Friday',
        date: '4 Apr',
        high: 23,
        low: 13,
        rain: 15,
        humidity: 55,
        wind: 12,
        condition: 'Clearing',
        icon: 'cloud-sun',
      },
    ],
    irrigationAdvisory: [
      {
        field: 'Field A',
        crop: 'Maize',
        today: 'Run',
        note: 'Normal schedule. Rain on Wednesday may offset future needs.',
        status: 'ok',
      },
      {
        field: 'Field B',
        crop: 'Tomatoes',
        today: 'Run - Urgent',
        note: 'Moisture is low enough that the rain window is too late to wait for.',
        status: 'warn',
      },
      {
        field: 'Field C',
        crop: 'Spinach',
        today: 'Skip',
        note: 'Current moisture is healthy and midweek rain should be enough.',
        status: 'ok',
      },
      {
        field: 'Field D',
        crop: 'Sorghum',
        today: 'Run - Critical',
        note: 'Run irrigation immediately for 4 hours at 6 L/hr.',
        status: 'alert',
      },
    ],
  },
};
